### ISSUE TITLE
Typo definición de función característica

### ISSUE THREAD

**Issue by Benja-Vera** [camilocarvajalreyes/MA4402-Simulacion-Estocastica#3]
Línea 528 de los preliminares. Reemplazar "sen" por "\sen". Además, sería bueno tener consistencia en el orden del producto interno <\xi, x>

**Comment by Benja-Vera** [comment]
Tampoco se entiende qué representa C en la propiedad 1.2.2 de la función característica.

**Comment by camilocarvajalreyes** [comment]
listo, corregido entre commits e5f7db1d4c78061b69085eeca1d5f7d09d1b8c14 y 4b3eea0327f81722504129c3599ef05b3876de4e

notar que C era un typo, más bien era 0:

$$ \varphi_\mu(0) = 1$$

es la propiedad en cuestión.
